[package]
name = "l2"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.12.0"
clap = { version = "4.5.53", features = ["derive"] }
l1 = { version = "0.1.0", path = "../l1" }
utils = { version = "0.1.0", path = "../utils" }

[[bin]]
name = "L2"
path = "src/main.rs"
